### ISSUE TITLE
Unable to provide password in connection option

### ISSUE THREAD

**Issue by MarketaAdamova** [xsc/kithara#1]
Hi,
there is issue with this fn which blocks 'password' to be used in connection options. Without it I was unable to use your lib to connect to RabbitMQ (and I d really like to use it :)

https://github.com/xsc/kithara/blob/master/src/kithara/protocols.clj#L135-L137

I have patch ready with one liner fix but I don't seem to be able to create new branch (permission denied to push).

Regards
  Marketa

**Comment by MarketaAdamova** [comment]
Nevermind I figure out I need to fork first. Will open the PR shortly.

**Comment by xsc** [comment]
Released in

``` clojure
[kithara "0.1.1"]
```

Thanks again!
